fn main() {
    // Only compile protobuf files if the gaggle feature is enabled
    #[cfg(feature = "gaggle")]
    compile_protos();

    // Existing build logic
    let version = rustc_version::version().unwrap();
    if version.major == 1 && version.minor < 64 {
        println!("cargo:rustc-cfg=rust_pre_164");
    }
}

#[cfg(feature = "gaggle")]
fn compile_protos() {
    println!("cargo:rerun-if-changed=proto/gaggle.proto");

    // Use just prost-build to compile protobuf files
    // The service stubs will be generated by prost and we'll use them directly
    prost_build::Config::new()
        .service_generator(Box::new(|config, _| {
            // Generate tonic service code
            tonic_build::configure().service_generator()
        }))
        .compile_protos(&["proto/gaggle.proto"], &["proto"])
        .unwrap_or_else(|e| panic!("Failed to compile protos: {}", e));
}
